language: julia
os:
  - linux
  - osx
julia:
  - 1.1
  - 1.2
  - 1.3
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
jobs:
  allow_failures:
    - script: bash ./docs/travis.sh
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script: bash ./docs/travis.sh
      after_success: skip
notifications:
  email: false
codecov: true
coveralls: true
