language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.1
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
    - os: windows
    - julia: nightly
  fast_finish: true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script: bash ./docs/travis.sh
      after_success: skip

notifications:
  email: false

codecov: true
coveralls: true
